package token;

public enum TokenType {
    STRING,BEGIN, END, PROGRAM, PROCEDURE, PARAM, RUN, OUT,
    CLOSE_BRACKET, OPEN_BRACKET, OPEN_BLOCK, CLOSE_BLOCK,
    PLUS, MINUS, MULTIPLY, DIVIDE, VAR, CONST,
    ASSIGNMENT,
    EQUAL, NOTEQUAL, GREATER, LESS,
    NUMBER,
    IF, ELSE,
    WHILE,
    PRINT, PRINTLN,
    SEMICOLON, COMMA, DOT, COLON,
    IDENTIFIER,
}